package com.quare.bibleplanner.core.provider.room.entity

import androidx.room3.Entity
import androidx.room3.Index
import androidx.room3.PrimaryKey

/**
 * A note written about a passage. The id is generated by the client so a note created offline keeps
 * its identity once it reaches the backend.
 *
 * The verses the note covers live in [VerseNoteVerseEntity] because they are payload, not identity:
 * extending a note from 3:1-3 to 3:1-5 keeps the same note. The version is payload for the same
 * reason — the note keeps its id — but it is indexed, because a chapter is read in one version.
 */
@Entity(
    tableName = "verse_notes",
    indices = [Index("bibleVersionId", "bookId", "chapterNumber")],
)
data class VerseNoteEntity(
    @PrimaryKey val id: String,
    val bibleVersionId: String,
    val bookId: String,
    val chapterNumber: Int,
    val text: String,
    val isDeleted: Boolean,
    val createdAtEpochMillis: Long,
    val updatedAtEpochMillis: Long,
    val isPendingSync: Boolean,
)
