package com.quare.bibleplanner.core.provider.room.entity

import androidx.room3.Entity

/**
 * A colour applied to a single verse. The row is keyed by the verse's canonical coordinates rather
 * than by [VerseEntity.id] so it survives a bible version re-download, which rebuilds the local
 * autogenerated ids, and so it maps directly onto the backend's primary key.
 *
 * [color] is null for a highlight the user removed: the sync engine never deletes rows, so the
 * removal has to travel as a tombstone carrying a fresh [updatedAtEpochMillis].
 */
@Entity(
    tableName = "verse_highlights",
    primaryKeys = ["bookId", "chapterNumber", "verseNumber"],
)
data class VerseHighlightEntity(
    val bookId: String,
    val chapterNumber: Int,
    val verseNumber: Int,
    val color: String?,
    val updatedAtEpochMillis: Long,
    val isPendingSync: Boolean,
)
