package com.quare.bibleplanner.feature.daystudy.domain.mapper

import com.quare.bibleplanner.core.model.book.BookId

class BookIdWireNameMapper {
    fun map(bookId: BookId): String = when (bookId) {
        BookId.GEN -> "GENESIS"
        BookId.EXO -> "EXODUS"
        BookId.LEV -> "LEVITICUS"
        BookId.NUM -> "NUMBERS"
        BookId.DEU -> "DEUTERONOMY"
        BookId.JOS -> "JOSHUA"
        BookId.JDG -> "JUDGES"
        BookId.RUT -> "RUTH"
        BookId.FIRST_SA -> "FIRST_SAMUEL"
        BookId.SECOND_SA -> "SECOND_SAMUEL"
        BookId.FIRST_KI -> "FIRST_KINGS"
        BookId.SECOND_KI -> "SECOND_KINGS"
        BookId.FIRST_CH -> "FIRST_CHRONICLES"
        BookId.SECOND_CH -> "SECOND_CHRONICLES"
        BookId.EZR -> "EZRA"
        BookId.NEH -> "NEHEMIAH"
        BookId.EST -> "ESTHER"
        BookId.JOB -> "JOB"
        BookId.PSA -> "PSALMS"
        BookId.PRO -> "PROVERBS"
        BookId.ECC -> "ECCLESIASTES"
        BookId.SNG -> "SONG_OF_SOLOMON"
        BookId.ISA -> "ISAIAH"
        BookId.JER -> "JEREMIAH"
        BookId.LAM -> "LAMENTATIONS"
        BookId.EZK -> "EZEKIEL"
        BookId.DAN -> "DANIEL"
        BookId.HOS -> "HOSEA"
        BookId.JOL -> "JOEL"
        BookId.AMO -> "AMOS"
        BookId.OBA -> "OBADIAH"
        BookId.JON -> "JONAH"
        BookId.MIC -> "MICAH"
        BookId.NAM -> "NAHUM"
        BookId.HAB -> "HABAKKUK"
        BookId.ZEP -> "ZEPHANIAH"
        BookId.HAG -> "HAGGAI"
        BookId.ZEC -> "ZECHARIAH"
        BookId.MAL -> "MALACHI"
        BookId.MAT -> "MATTHEW"
        BookId.MRK -> "MARK"
        BookId.LUK -> "LUKE"
        BookId.JHN -> "JOHN"
        BookId.ACT -> "ACTS"
        BookId.ROM -> "ROMANS"
        BookId.FIRST_CO -> "FIRST_CORINTHIANS"
        BookId.SECOND_CO -> "SECOND_CORINTHIANS"
        BookId.GAL -> "GALATIANS"
        BookId.EPH -> "EPHESIANS"
        BookId.PHP -> "PHILIPPIANS"
        BookId.COL -> "COLOSSIANS"
        BookId.FIRST_TH -> "FIRST_THESSALONIANS"
        BookId.SECOND_TH -> "SECOND_THESSALONIANS"
        BookId.FIRST_TI -> "FIRST_TIMOTHY"
        BookId.SECOND_TI -> "SECOND_TIMOTHY"
        BookId.TIT -> "TITUS"
        BookId.PHM -> "PHILEMON"
        BookId.HEB -> "HEBREWS"
        BookId.JAS -> "JAMES"
        BookId.FIRST_PE -> "FIRST_PETER"
        BookId.SECOND_PE -> "SECOND_PETER"
        BookId.FIRST_JN -> "FIRST_JOHN"
        BookId.SECOND_JN -> "SECOND_JOHN"
        BookId.THIRD_JN -> "THIRD_JOHN"
        BookId.JUD -> "JUDE"
        BookId.REV -> "REVELATION"
    }
}
