package com.quare.bibleplanner.core.provider.analytics.domain.model

object AnalyticsEventNames {
    const val DESTINATION_VIEW = "destination_view"

    const val CHAPTER_READ_TOGGLED = "chapter_read_toggled"
    const val DAY_READ_TOGGLED = "day_read_toggled"
    const val BOOK_READ_TOGGLED = "book_read_toggled"
    const val BOOK_COMPLETED = "book_completed"
    const val WEEK_COMPLETED = "week_completed"
    const val PLAN_COMPLETED = "plan_completed"
    const val BIBLE_PROGRESS_MILESTONE = "bible_progress_milestone"
    const val READING_STREAK_MILESTONE = "reading_streak_milestone"
    const val BOOK_FAVORITE_TOGGLED = "book_favorite_toggled"
    const val PLAN_SELECTED = "plan_selected"
    const val PLAN_START_DATE_CHANGED = "plan_start_date_changed"
    const val READ_DATE_EDITED = "read_date_edited"
    const val PROGRESS_RESET_CONFIRMED = "progress_reset_confirmed"
    const val PROGRESS_RESET_CANCELLED = "progress_reset_cancelled"
    const val READING_SUGGESTION_CLICKED = "reading_suggestion_clicked"

    const val NOTE_SAVED = "note_saved"
    const val NOTE_DELETED = "note_deleted"
    const val NOTES_LIMIT_REACHED = "notes_limit_reached"

    const val DAY_STUDY_CARD_CLICKED = "day_study_card_clicked"
    const val DAY_STUDY_GENERATION_STARTED = "day_study_generation_started"
    const val DAY_STUDY_GENERATION_COMPLETED = "day_study_generation_completed"
    const val DAY_STUDY_GENERATION_FAILED = "day_study_generation_failed"
    const val DAY_STUDY_OPENED = "day_study_opened"

    const val BIBLE_VERSION_SELECTED = "bible_version_selected"
    const val BIBLE_VERSION_DOWNLOAD_STARTED = "bible_version_download_started"
    const val BIBLE_VERSION_DOWNLOAD_COMPLETED = "bible_version_download_completed"
    const val BIBLE_VERSION_DOWNLOAD_FAILED = "bible_version_download_failed"
    const val BIBLE_VERSION_DOWNLOAD_PAUSED = "bible_version_download_paused"
    const val BIBLE_VERSION_DELETED = "bible_version_deleted"

    const val PAYWALL_VIEWED = "paywall_viewed"
    const val PAYWALL_PLAN_SELECTED = "paywall_plan_selected"
    const val PURCHASE_STARTED = "purchase_started"
    const val PURCHASE_COMPLETED = "purchase_completed"
    const val PURCHASE_FAILED = "purchase_failed"
    const val RESTORE_COMPLETED = "restore_completed"
    const val RESTORE_FAILED = "restore_failed"
    const val PAYWALL_DISMISSED = "paywall_dismissed"
    const val DONATION_METHOD_COPIED = "donation_method_copied"
    const val GITHUB_SPONSORS_OPENED = "github_sponsors_opened"
    const val DONATION_SECTION_TOGGLED = "donation_section_toggled"
    const val PIX_QR_SHARED = "pix_qr_shared"

    const val LOGIN = "login"
    const val LOGIN_STARTED = "login_started"
    const val LOGIN_FAILED = "login_failed"
    const val LOGIN_CANCELLED = "login_cancelled"
    const val LOGOUT_CONFIRMED = "logout_confirmed"
    const val LOGOUT_FAILED = "logout_failed"
    const val LOGIN_NUDGE_SHOWN = "login_nudge_shown"
    const val LOGIN_NUDGE_ACCEPTED = "login_nudge_accepted"
    const val LOGIN_NUDGE_SNOOZED = "login_nudge_snoozed"
    const val LOGIN_NUDGE_DISABLED = "login_nudge_disabled"
    const val LOGIN_WARNING_SHOWN = "login_warning_shown"
    const val LOGIN_WARNING_ACCEPTED = "login_warning_accepted"
    const val LOGIN_WARNING_DISMISSED = "login_warning_dismissed"
    const val SYNC_COMPLETED = "sync_completed"
    const val SYNC_FAILED = "sync_failed"
    const val CONNECTED_DEVICES_TOGGLED = "connected_devices_toggled"
    const val DEVICE_SIGNED_OUT = "device_signed_out"
    const val DEVICE_RENAMED = "device_renamed"
    const val DEVICE_RENAME_CANCELLED = "device_rename_cancelled"

    const val MORE_OPTION_CLICKED = "more_option_clicked"
    const val RATE_APP_REVIEW_REQUESTED = "rate_app_review_requested"
    const val THEME_CHANGED = "theme_changed"
    const val CONTRAST_CHANGED = "contrast_changed"
    const val DYNAMIC_COLORS_TOGGLED = "dynamic_colors_toggled"
    const val SETTING_SYNC_TOGGLED = "setting_sync_toggled"
    const val LANGUAGE_CHANGED = "language_changed"
    const val NOTIFICATION_PERMISSION_RESULT = "notification_permission_result"
    const val NOTIFICATION_PERMISSION_PROMPTED = "notification_permission_prompted"
    const val NOTIFICATION_OPENED = "notification_opened"
    const val RELEASE_NOTES_TAB_SELECTED = "release_notes_tab_selected"
    const val GITHUB_RELEASE_OPENED = "github_release_opened"
    const val CONTACT_SUPPORT_EMAIL_OPENED = "contact_support_email_opened"
    const val CONTACT_SUPPORT_EMAIL_COPIED = "contact_support_email_copied"

    const val UPDATE_PROMPT_SHOWN = "update_prompt_shown"
    const val UPDATE_ACCEPTED = "update_accepted"
    const val UPDATE_DISMISSED = "update_dismissed"
    const val UPDATE_DOWNLOAD_FAILED = "update_download_failed"
    const val UPDATE_INSTALL_STARTED = "update_install_started"

    const val BOOKS_SEARCH_USED = "books_search_used"
    const val BOOKS_FILTER_TOGGLED = "books_filter_toggled"
    const val BOOKS_SORT_CHANGED = "books_sort_changed"
    const val BOOKS_LAYOUT_CHANGED = "books_layout_changed"
    const val TESTAMENT_SWITCHED = "testament_switched"
    const val WEB_APP_LINK_OPENED = "web_app_link_opened"
    const val SYNOPSIS_TOGGLED = "synopsis_toggled"
    const val PLAN_WEEK_TOGGLED = "plan_week_toggled"
    const val PLAN_GROUP_TOGGLED = "plan_group_toggled"
    const val PLAN_SHORTCUT_USED = "plan_shortcut_used"
}
