package com.quare.bibleplanner.core.provider.room.relation

/**
 * Projection of a verse pending read-state sync, joined with its chapter so the row carries the
 * stable cross-device identity (book id + chapter number + verse number) instead of the local
 * autogenerated `chapterId`.
 */
data class PendingVerseRead(
    val bookId: String,
    val chapterNumber: Int,
    val verseNumber: Int,
    val isRead: Boolean,
    val readUpdatedAt: Long?,
)
