package com.quare.bibleplanner.core.provider.room.relation

// Why: joined with the chapter so the row carries a stable cross-device identity (book, chapter,
// verse) instead of the local autogenerated chapterId.
data class PendingVerseRead(
    val bookId: String,
    val chapterNumber: Int,
    val verseNumber: Int,
    val isRead: Boolean,
    val readUpdatedAt: Long?,
)
